### ISSUE TITLE
Duplicates may occur in replica table for MySQL-BigQuery connector

### ISSUE THREAD

**Issue by schalkva** [GoogleCloudPlatform/DataflowTemplates#127]
Some transactions come in with the same timestampMs and PK's on the changelog table and causes errors with the merge process. This seems to be happening when rapid transactions occur on the source and the precision is insufficient for timestampMs. 

This causes the merge to insert an operation that is equal to update as it only checks for not equal delete.  Errors are resolved by changing WHEN NOT MATCHED BY TARGET AND changelog.operation !="DELETE" THEN to WHEN NOT MATCHED BY TARGET AND changelog.operation ="INSERT" THEN

**Comment by pabloem** [comment]
thanks for finding that issue! would you be interested in submiting a pull request?

**Comment by pabloem** [comment]
(if not, I can look into this, but we'll welcome your submission as well)

**Comment by hktv-mkchoi** [comment]
The solution may not work when the latest changelog record is already UPDATE

**Comment by schalkva** [comment]
just waiting on some feedback regarding the data in the replica tables on our side, I'll submit the pull request as soon as the data is confirmed to be clean. we've been error free thus far at least.

**Comment by dzoellner** [comment]
Ran into the same problem where there were multiple rows in the changelog tables with the same primarykey and timestamp. This breaks the merge query in bigquery and throws `BigQueryException:` UPDATE/MERGE must match at most one source row for each target row` . This causes the replica tables to stop being updated as each subsequent merge statement fails.

There's no change to the query that can, in every situation, choose the correct row to merge with, because it doesn't know the order in which they happened. So, the only real fix for this is to change what the tool uses to determine order. Maybe debezium offset? Maybe change debezium to guarantee a unique/incremented timestamp?

**Comment by tai-huu-tran** [comment]
`DebeziumSourceRecordToDataflowCdcFormatTranslator.translate`: Using `recordValue.getStruct("source").getInt64("ts_ms")` instead of `recordValue.getInt64("ts_ms")` give a better order gaurantee, thought.

**Comment by pabloem** [comment]
I've added a change to avoid the errors on duplicates, although we are still ordering on the timestamp reported by debezium.
