### ISSUE TITLE
Publish this to Maven

### ISSUE THREAD

**Issue by ericandrewmeadows** [GoogleCloudPlatform/DataflowTemplates#157]
This should be able to be published to Maven so versions can be pinned.  Using Maven is common, and will allow this to be more usable...

**Comment by llamasoft** [comment]
There are also a few _very_ useful classes in here like FailsafeElement which could be a staple of Dataflow pipelines.  Currently it's a major hassle to incorporate it into pipelines because there's no officially published package for it.

**Comment by sabhyankar** [comment]
Hi @ericandrewmeadows  - We are using the repository to allow users to create their own customized pipelines based on the [Google Provided Templates](https://cloud.google.com/dataflow/docs/guides/templates/provided-templates). The base pipelines themselves could be run by specifying a release (or using ```latest```). For example, ```gs://dataflow-templates/2020-05-13-00_RC00/Cloud_PubSub_to_GCS_Text```.

We will take a look at providing a running release list that at least provides a list of changes in every release. This should hopefully provide some more visibility on what has changed in a specific release.

**Comment by sabhyankar** [comment]
Hi @llamasoft - Good point on the difficulty in reusing some of the useful classes. We could look at the possibility of adding that to upstream Apache Beam to make it easier to incorporate them into pipelines. Can you perhaps list some of the other ones you have found to be useful?

**Comment by llamasoft** [comment]
The KafkaIO modifications to accept ValueProviders are of great value, but I see it was integrated from an [upstream PR that was closed](https://github.com/apache/beam/pull/6636).  Still, it would be helpful to have it accessible as ValueProviders being required for Dataflow Templates is somewhat of a blocker.

**Comment by sabhyankar** [comment]
Hi @llamasoft - With the release of the new [Flex template feature](https://cloud.google.com/dataflow/docs/guides/templates/using-flex-templates), we would not need support for ValueProviders in order to create a templated pipeline. This feature will allow us to convert any Dataflow pipeline into a template without having to worry about some of the earlier limitations.

Take a look at the [Pub/Sub Avro to BigQuery](https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/pubsub-binary-to-bigquery) pipeline for a Flex template example. 

We will briefly talk about this feature at the upcoming [Beam summit](https://2020.beamsummit.org/sessions/dataflow-flex-templates/) and should hopefully follow that up with some more details documentation. Stay tuned!

**Comment by djmittens** [comment]
Hello, i saw this issue was closed, but are these packaged published to mvn central or some repository i can grab them from? im looking to create customization to some google cloud to google cloud pipelines, and i cant see them published anywhere.
