### ISSUE TITLE
[Bug]: Cannot use SASL_PLAIN for connection to Kafka

### ISSUE THREAD

**Issue by ktrieu** [GoogleCloudPlatform/DataflowTemplates#1607]
### Related Template(s)

kafka_to_bigquery

### Template Version

2024-05-13-00_rc00

### What happened?

I'm trying to get the Kafka to BigQuery template to connect to a Kafka cluster hosted on Confluent.

However, the template fails to connect to the cluster and times out reading the topic metadata. I spun up a VM in Compute Engine attached to the `default` network (which I'm also using for the Dataflow workers) and managed to connect to the cluster correctly, so I don't think it's a connectivity issue.

I believe that this is because the template is trying to connect with `PLAINTEXT` instead of `SASL_PLAINTEXT`. This log indicates that `security.protocol` is set to `PLAINTEXT` when the Kafka client starts:

```
org.apache.kafka.clients.consumer.ConsumerConfig - ConsumerConfig values: 
        ...
	security.protocol = PLAINTEXT
        ...
```

There's a `kafkaReadAuthenticationMode` in `KafkaReadOptions.java` that's defaulted to `NONE`. I've tried to set it to `SASL_PLAIN` via the command line but I get an "unrecognized parameter" error.

How do I get the template to use `SASL_PLAIN` authentication? Or am I misunderstanding my issue?

### Relevant log output

```shell
org.apache.kafka.clients.consumer.ConsumerConfig - ConsumerConfig values: 
	allow.auto.create.topics = true
	auto.commit.interval.ms = 5000
	auto.offset.reset = earliest
	bootstrap.servers = [pkc-2396y.us-east-1.aws.confluent.cloud:9093]
	check.crcs = true
	client.dns.lookup = use_all_dns_ips
	client.id = consumer-null-1
	client.rack = 
	connections.max.idle.ms = 540000
	default.api.timeout.ms = 60000
	enable.auto.commit = false
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = null
	group.instance.id = null
	heartbeat.interval.ms = 3000
	interceptor.classes = []
	internal.leave.group.on.close = true
	internal.throw.on.fetch.stable.offset.unsupported = false
	isolation.level = read_uncommitted
	key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 524288
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	security.providers = null
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer

---

com.google.cloud.teleport.v2.common.UncaughtExceptionLogger - The template launch failed.
java.lang.RuntimeException: org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata
	at org.apache.beam.runners.dataflow.ReadTranslator.translateReadHelper(ReadTranslator.java:55)
	at org.apache.beam.runners.dataflow.DataflowRunner$StreamingUnboundedRead$ReadWithIdsTranslator.translate(DataflowRunner.java:2213)
	at org.apache.beam.runners.dataflow.DataflowRunner$StreamingUnboundedRead$ReadWithIdsTranslator.translate(DataflowRunner.java:2208)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$Translator.visitPrimitiveTransform(DataflowPipelineTranslator.java:502)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:593)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:585)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:585)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:585)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:585)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:585)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.access$500(TransformHierarchy.java:240)
	at org.apache.beam.sdk.runners.TransformHierarchy.visit(TransformHierarchy.java:214)
	at org.apache.beam.sdk.Pipeline.traverseTopologically(Pipeline.java:477)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$Translator.translate(DataflowPipelineTranslator.java:434)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator.translate(DataflowPipelineTranslator.java:188)
	at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:1270)
	at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:202)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:325)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:310)
	at com.google.cloud.teleport.v2.templates.KafkaToBigQuery.runJsonPipeline(KafkaToBigQuery.java:435)
	at com.google.cloud.teleport.v2.templates.KafkaToBigQuery.run(KafkaToBigQuery.java:347)
	at com.google.cloud.teleport.v2.templates.KafkaToBigQuery.main(KafkaToBigQuery.java:284)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata
```

**Comment by an2x** [comment]
The existing [KafkaToBigQuery template](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQuery.java) doesn't support any authentication at all. The `kafkaReadAuthenticationMode` parameter was exposed in it by accident (this is a bug), that's why setting it to SASL_PLAIN results in an "unrecognized parameter" error.

There is a new [KafkaToBigQueryFlex](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlex.java) template in development that is going to support different authentication options.

**Comment by ktrieu** [comment]
Ah, I see, I was confusing the two. Is there a timeline on when the new template might be ready? Or does it make more sense for me to extend the original to support my use case?

**Comment by liferoad** [comment]
I suggest you wait for the new template, which should be available in early June.

**Comment by ktrieu** [comment]
I just took a look at the Dataflow console again and the Kafka to BigQuery template now has the authentication mode parameter - is this the new template you were talking about?

**Comment by ktrieu** [comment]
Wondering if there were any updates on this issue - I notice the Kafka to BigQuery template on DataFlow has changed, but it seems to be missing UDF support, which is required for my use-case.

**Comment by an2x** [comment]
Yes, the new template doesn't support UDF. The reason is that it supports a lot of other stuff that makes schema management tricky. E.g. you can read messages with different schema from the same topic, and write them to different BQ tables (or the same BQ table with a superset of fields). Now, if a UDF modifies the messages, we'll have to know the output schema of every message, which is hard to support with the current template architecture (users would need to provide some kind of a map: the UDF output schema for every source schema version).

The old template supports UDF (because it's simpler in general and can process only messages in a single schema), but it doesn't support other feature. The old template is still available, it's just not included in the drop-down list in the UI. You can launch it via gcloud/REST API, or from the UI by choosing "Custom Template" from the drop-down list and using `gs://dataflow-templates-<region>/latest/flex/Kafka_to_BigQuery` as the path.

You can also just fork one of the existing templates and write your own pipeline, if neither of them have all the features you need.

I'm going to close this issue as the original problem (SASL_PLAIN not working) is resolved.
