### ISSUE TITLE
GCS Avro to BigQuery

### ISSUE THREAD

**Issue by PramodKejriwal** [GoogleCloudPlatform/DataflowTemplates#17]
This is not a issue, but a question. In absence of any other method, asking my question in form of issue. Sorry for that. Here goes the question:

Will the code GCS Avro to BigTable work for BQ also? Is there anything I should take take of, before applying it for a BQ case?

Thanks much
Pramod

**Comment by rjerrems** [comment]
Hi Pramod,

You can actually use the BQ API to load Avro files from GCS using a BQ job. See the following documentation:

https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-avro

Hope this helps!

**Comment by bvolpato** [comment]
We now also have [PubsubAvroToBigQuery](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/pubsub-binary-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/PubsubAvroToBigQuery.java), which can be handy if you need to use Dataflow.


This issue was stale for some time. Please reopen it if there is a follow up or any related questions.
