### ISSUE TITLE
BQ to GCS Avro or Parquet

### ISSUE THREAD

**Issue by darrenhaken** [GoogleCloudPlatform/DataflowTemplates#19]
Any plans to support this? I wanted to be able to have an incremental unload from BA to GCS to see with Apache Spark

**Comment by rjerrems** [comment]
Hi @darrenhaken - not sure if this will help, but it is possible to export from BQ to GCS in Avro format using a BQ export job. See the following doc:

https://cloud.google.com/bigquery/docs/exporting-data#avro_export_details

Thanks

**Comment by rjerrems** [comment]
There is an outstanding feature request to export to Parquet, which would be great to add your upvote / voice to https://issuetracker.google.com/80464233. 

Details issue tracker are available here if you have not used it before. https://cloud.google.com/support/docs/issue-trackers

**Comment by darrenhaken** [comment]
@rjerrems thanks I'll add my comments right now

**Comment by bvolpato** [comment]
We now support [BigQueryToParquet](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/bigquery-to-parquet/src/main/java/com/google/cloud/teleport/v2/templates/BigQueryToParquet.java).


This issue was stale for some time. Please reopen it if there is a follow up or any related questions.
