### ISSUE TITLE
Deadletter table or topic?

### ISSUE THREAD

**Issue by bartaelterman** [GoogleCloudPlatform/DataflowTemplates#246]
Hello,

Why is the [`KafkaToBigQuery.java`](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQuery.java) template using a BigQuery table as dead-letter instead of a Pub/Sub topic?

To give my question some context:

We are using this template but we want to monitor how many / when messages are sent to the dead-letter. Since the dead-letter is a BigQuery table, we thought using the standard BigQuery monitoring metric  `storage/uploaded_row_count` would be useful. However, as documented [here](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-bigquery)  that metric has a latency of 21k seconds (~6 hours) which is too much for us.

Hence, we're looking for an alternative and it seems to be more a common practice to use Pub/Sub as a dead-letter output (as it seems there are even [dead-letter topics these days](https://cloud.google.com/pubsub/docs/handling-failures) ). Pub/Sub monitoring metrics only have a latency of about 4 minutes.

That's why I wonder why you chose to use BigQuery in this template since it seems harder to monitor that. I know we can fix our issue by creating our own pipeline and writing to Pub/Sub ourselves. But maybe there's a rationale I don't know of and I'm trying to do the wrong thing.

**Comment by prathapreddy123** [comment]
Historically either BQ table or Pub/Sub topic is used as dead letter sink depending on context.  Since BQ is the sink type in KakfaToBigQuery the same type has been used even for storing dead letter records.  With Flex templates capable of supporting the option to chose dynamic sink type (i.e BQ Table or Pub/Sub Topic) based on user's choice during template launch time, we consider adding support for both sink types.

**Comment by bartaelterman** [comment]
Ok, cool. Thanks!
