### ISSUE TITLE
[Bug]: KvCoder(StringUtf8Coder,TableRowJsonCoder) is not deterministic because:  Value coder must be deterministic

### ISSUE THREAD

**Issue by arijitdas2** [GoogleCloudPlatform/DataflowTemplates#364]
### Related Template(s)

DLPTextToBigQueryStreaming

### What happened?

getting following error when writing to BigQuery table - 

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project apache-beam-wf-dlp: An exception occured while executing the Java class. the keyCoder of a GroupByKey must be deterministic: KvCoder(StringUtf8Coder,TableRowJsonCoder) is not deterministic because:
[ERROR]         Value coder must be deterministic: TableRowJsonCoder is not deterministic because:
[ERROR]         TableCell can hold arbitrary instances, which may be non-deterministic.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project apache-beam-wf-dlp: An exception occured while executing the Java class. the keyCoder of a GroupByKey must be deterministic
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)

### Beam Version

2.35.0

**Comment by chitara-01** [comment]
@bvolpato 

Entire stack trace for your reference:

`com.google.cloud.teleport.v2.common.UncaughtExceptionLogger - The template launch failed. java.lang.IllegalArgumentException: ParDo requires a deterministic key coder in order to use state and timers at org.apache.beam.sdk.transforms.ParDo.validateStateApplicableForInput(ParDo.java:448) at org.apache.beam.sdk.transforms.ParDo.access$300(ParDo.java:394) at org.apache.beam.sdk.transforms.ParDo$MultiOutput.expand(ParDo.java:953) at org.apache.beam.sdk.transforms.ParDo$MultiOutput.expand(ParDo.java:872) at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:548) at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:482) at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:360) at org.apache.beam.sdk.transforms.ParDo$SingleOutput.expand(ParDo.java:797) at org.apache.beam.sdk.transforms.ParDo$SingleOutput.expand(ParDo.java:712) at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:548) at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:482) at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:360) at org.apache.beam.sdk.transforms.GroupIntoBatches.expand(GroupIntoBatches.java:340) at org.apache.beam.sdk.transforms.GroupIntoBatches.expand(GroupIntoBatches.java:104) at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:548) at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:499) at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:373) at org.apache.beam.sdk.io.gcp.bigquery.StorageApiLoads.expandTriggered(StorageApiLoads.java:217) at org.apache.beam.sdk.io.gcp.bigquery.StorageApiLoads.expand(StorageApiLoads.java:107) at org.apache.beam.sdk.io.gcp.bigquery.StorageApiLoads.expand(StorageApiLoads.java:44) at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:548) at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:499) at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:373) at org.apache.beam.sdk.io.gcp.bigquery.BigQueryIO$Write.continueExpandTyped(BigQueryIO.java:3434) at org.apache.beam.sdk.io.gcp.bigquery.BigQueryIO$Write.expandTyped(BigQueryIO.java:3257) at org.apache.beam.sdk.io.gcp.bigquery.BigQueryIO$Write.expand(BigQueryIO.java:3153) at org.apache.beam.sdk.io.gcp.bigquery.BigQueryIO$Write.expand(BigQueryIO.java:2122) at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:548) at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:499) at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:373) at com.google.cloud.teleport.v2.templates.DLPTextToBigQueryStreaming.run(DLPTextToBigQueryStreaming.java:244) at com.google.cloud.teleport.v2.templates.DLPTextToBigQueryStreaming.main(DLPTextToBigQueryStreaming.java:158)`
