### ISSUE TITLE
[Feature Request]: User-defined functions (UDFs) support for PubsubToPubsub template

### ISSUE THREAD

**Issue by arneesh** [GoogleCloudPlatform/DataflowTemplates#424]
### Related Template(s)

PubsubToPubsub

### What feature(s) are you requesting?

Could the UDF support be added to this template(PubsubToPubsub)? If not, then at least for the time being can the necessary converters be provided so that I can create the template myself?

**Comment by bvolpato** [comment]
I gave that a first attempt (https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1267), but PubsubToPubsub is a classic template and there's no way to add  an "optional" branch, otherwise all existing usage would regress/fail until deadletter topic is given.

We'll first need to move PubsubToPubsub to a Flex template, and just in that case (if UDF is passed) use that branch, and just in case a deadletter topic is passed, to instantiate that sink.
