### ISSUE TITLE
Pub/Sub to BigQuery Errors PayloadString is not valid JSON

### ISSUE THREAD

**Issue by fra-c** [GoogleCloudPlatform/DataflowTemplates#43]
The errors from the [Cloud Pub/Sub Subscription to BigQuery](https://cloud.google.com/dataflow/docs/guides/templates/provided-streaming#cloudpubsubsubscriptiontobigquery) template aren't saved as valid JSON in the PayloadString column and I am unable to replay them.

It looks like this:
`
{event={userId=1234, sessionEvent={sessionId=DSFG, ua=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36, browser={name=Chrome, version=74.0.3729.131, major=74}}}
`

If this is intended, how do I convert it and push it back to Pub/Sub?

**Comment by sabhyankar** [comment]
Hi fra-c - This is due to how the insertErrors are wrapper [here](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/src/main/java/com/google/cloud/teleport/templates/PubSubToBigQuery.java#L289) with the main issue being in [this](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/src/main/java/com/google/cloud/teleport/templates/TextToBigQueryStreaming.java#L265-L281) method. There is a PR that is currently being reviewed. Once the [PR](https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/36) is merged and a release is cut, it should solve this problem as well.

**Comment by bddckr** [comment]
We've been hit by this same issue and are looking at plenty of gigabytes of error data to parse ourselves due to this.

What's the status of this issue/the linked PR?

**Comment by Hechamon** [comment]
We just ran into this problem as well and have a few million rows of errors that we would really like to recover. Did any of you write a regex or something that can recreate valid Json?
Any language, any technology is fine. Please?
