### ISSUE TITLE
[Bug]: Datastream to BigQuery All the Data Types are converted to string

### ISSUE THREAD

**Issue by atateim** [GoogleCloudPlatform/DataflowTemplates#459]
### Related Template(s)

dataflow flex template (Datastream to BigQuery)

### What happened?

dataflow is converting all the data types to string and capture them as string in BigQuery

### Beam Version

2.35.0

### Relevant log output

```shell
public TableSchema getSchema(KV<TableId, TableRow> destination) {

      TableRow bqRow = destination.getValue();
      TableSchema schema = new TableSchema();
      List<TableFieldSchema> fields = new ArrayList<TableFieldSchema>();
      List<TableCell> cells = bqRow.getF();
      /** currently all BQ data types are set to String */
      for (Map<String, Object> object : cells) {
        String header = object.keySet().iterator().next();
        /** currently all BQ data types are set to String */
        // Why do we use checkHeaderName here and not elsewhere, TODO if we add this back in
        // fields.add(new TableFieldSchema().setName(checkHeaderName(header)).setType("STRING"));
        fields.add(new TableFieldSchema().setName(header).setType("STRING"));
```

**Comment by ankitMukhija** [comment]
We are facing the same bug , so checking in if there is any workaround or is it resolved?

**Comment by dani29** [comment]
Hi Ankit,

This is the existing behavior of Datastream template to convert types to STRINGs if the source database was unavailable at the time we tried to fetch the actual schema. Without any details or logs, this bug is not actionable.

I suggest working with your account team and filling a support case, where you could provide all the project details that will allow looking into it, based on your organization's support tier.

**Comment by trentkgUjet** [comment]
@dani29  what details or logs do you need? I also want this to get fixed and this currently happens to me. 

Also I'm surprised we need access to the source database to get this fixed in my case since we're using AVRO. This should have the entire schema available, yes?
