### ISSUE TITLE
[Feature Request]: Bigquery to Elasticsearch transform UDF

### ISSUE THREAD

**Issue by imranolas** [GoogleCloudPlatform/DataflowTemplates#598]
### Related Template(s)

BigQuery to Elasticsearch

### What feature(s) are you requesting?

The ability to specify a Javascript UDF to transform extracted rows from Bigquery into a rich JSON document for Elasticsearch. I would expect the function to be executed for each row from the source and to return a valid serializable object or JSON.

**Comment by imranolas** [comment]
Thanks so much for adding support for this. 

Unfortunately, I'm having trouble getting the template to run. I can see the transform step appears in the the DAG but the launch config doesn't accept the required parameters; `javascriptTextTransformGcsPath` or `javascriptTextTransformFunctionName`.

**Comment by bvolpato** [comment]
@imranolas Sorry, shouldn't have closed this yet. There is an internal update step to allow the parameters to be passed to the template. 

Since you can already see the graph, we should be able to make a copy of the template file and add those parameters to the metadata to expedite this:


```
      {
        "name": "javascriptTextTransformGcsPath",
        "label": "Cloud Storage location of your JavaScript UDF",
        "helpText": "The full URL of your .js file. Example: gs://your-bucket/your-function.js",
        "isOptional": true,
        "regexes": [
          "^gs:\\/\\/[^\\n\\r]+$"
        ],
        "paramType": "JAVASCRIPT_UDF_FILE"
      },
      {
        "name": "javascriptTextTransformFunctionName",
        "label": "The name of the JavaScript function you wish to call as your UDF",
        "helpText": "The function name should only contain letters, digits and underscores. Example: 'transform' or 'transform_udf1'.",
        "isOptional": true,
        "regexes": [
          "[a-zA-Z0-9_]+"
        ],
        "paramType": "TEXT"
      }
```

I went ahead and have done that for you, and uploaded to `gs://dataflow-staging-us-central1-fix/latest/flex/BigQuery_to_Elasticsearch`. If you are using from the UI, please use the option `Custom Template` and point to that path.

**Comment by bvolpato** [comment]
Will be out by the end of this week
