### ISSUE TITLE
PubSub to BigQuery Javascript UDF destroys attributes

### ISSUE THREAD

**Issue by mollyporph** [GoogleCloudPlatform/DataflowTemplates#69]
Hi,
We're using the PubSub Subscription to bigquery template. We have data in both PubSubMessage Attributes and the body. Our body contains an array without a field name i.e 
```json
[
 {"id": "item1"},
 {"id": "item2"}
]
```
Which the template had issues parsing, so we added a simple UDF
```javascript
function process(str){
    var arrayOfItems = JSON.parse(str);
    var outObject = {items: arrayOfItems};
    return JSON.stringify(outObject);
```
When this template runs it seems like the attributes are discarded after the UDF step.

I'm not that well versed with BEAM but it seems that when the `InvokeUDF` step is built it's discarding everything but the message payload
```java
 PCollectionTuple udfOut =
          input
              // Map the incoming messages into FailsafeElements so we can recover from failures
              // across multiple transforms.
              .apply("MapToRecord", ParDo.of(new PubsubMessageToFailsafeElementFn()))
              .apply(
                  "InvokeUDF",
                  FailsafeJavascriptUdf.<PubsubMessage>newBuilder()
                      .setFileSystemPath(options.getJavascriptTextTransformGcsPath())
                      .setFunctionName(options.getJavascriptTextTransformFunctionName())
                      .setSuccessTag(UDF_OUT)
                      .setFailureTag(UDF_DEADLETTER_OUT)
                      .build());
```
The  PubsubMessageToFailsafeElementFn looks like this
```java
 static class PubsubMessageToFailsafeElementFn
      extends DoFn<PubsubMessage, FailsafeElement<PubsubMessage, String>> {
    @ProcessElement
    public void processElement(ProcessContext context) {
      PubsubMessage message = context.element();
      context.output(
          FailsafeElement.of(message, new String(message.getPayload(), StandardCharsets.UTF_8)));
    }
  }
```
It seems to call `message.getPlayload` which would probably cause the issue.

So my question is: Am I doing something wrong, is there some way of getting both the attributes and the payload through the UDF? Or do I have to modify the java template?

Thanks in advance!

**Comment by Joao-Lamesa** [comment]
I am currently working in the same issue. 

I customized the PubsubMessageToFailsafeElementFn() method. I just added a few lines to add the attribute map to the main payload.

Hence, for me using the javascript udf woudn´t bring any gains, because we have to customize the failsafe element anyway. SO I might as well stick to it and make the transforms in that method itself. And I don´t have to pass and write udf again.

I hope it helps to clarify your work.

**Comment by dc185333** [comment]
Hi @Joao-Lamesa could you share what changes you made in order to add the attribute map to the main payload? We're running into a similar issue with being unable to access the attributes in the UDF and it seems like it would make more sense to just process the extension in the template instead of using a UDF at this point.
