### ISSUE TITLE
[Bug]: PubsubToAvro template parameters useSubscription and inputSubscription can't be used

### ISSUE THREAD

**Issue by Lizzfox** [GoogleCloudPlatform/DataflowTemplates#723]
### Related Template(s)

PubsubToAvro

### Context
The template has the `useSubscription` parameter which is always `false`, and there is the `inputSubscription` parameter, which is currently marked as `skipOptions` and cannot be passed while setting the template up.

### What was done?
Tried to read the backlog from the subscription. After removing the `skipOption` and staging the new template version separately in own bucket, couldn't use the `inputSubscription` parameter.

### Beam Version

Newer than 2.46.0

### Relevant log output

```shell
The workflow could not be created. Causes: (6693910a119d8d8): Found unexpected parameters: ['inputSubscription' (perhaps you meant 'useSubscription')]
```

**Comment by Abacn** [comment]
CC: @pranavbhandari24 @bvolpato related to load test

**Comment by pranavbhandari24** [comment]
Ah, this is because this is a classic template. We use this method in other templates as well and release 2 versions of the same template - one which accepts a topic, and another which accepts a subscription (e.g Pub/Sub to BigQuery).

Pub/Sub to Avro follows the same pattern but we only release the version which accepts a subscription.

**Comment by pranavbhandari24** [comment]
Added a Pub/Sub to Avro flex template in https://github.com/GoogleCloudPlatform/DataflowTemplates/commit/7b624a7e2c2629849bb14f525a2f65e742703d12
