### ISSUE TITLE
ZIP compression in Bulk Compress Cloud Storage Files template

### ISSUE THREAD

**Issue by zstatmanweil** [GoogleCloudPlatform/DataflowTemplates#87]
I would like to use the ZIP compression type in the Bulk Compress Cloud Storage Files Template, which the documentation states is a viable option:
![image](https://user-images.githubusercontent.com/37987755/75931974-21174800-5e2b-11ea-9daf-7e20bde9f5a0.png)

However, it is not an option when running the template through GCP-Dataflow though. 

Are there plans to make this an option? If not, the documentation should be updated.

Thank you!

**Comment by sabhyankar** [comment]
Good catch. I am not sure why that would be the case, let me take a look and get back to you.

**Comment by sabhyankar** [comment]
Looks like it is because the sdk [doesnt support ](https://github.com/apache/beam/blob/5369582826129ac914c000e555c8d2b43b42516c/sdks/java/core/src/main/java/org/apache/beam/sdk/io/Compression.java#L129)writing Zip files. I will have the documentation updated! Thank you for bringing this to our attention @zstatmanweil

**Comment by abhishesh** [comment]
> Looks like it is because the sdk [doesnt support ](https://github.com/apache/beam/blob/5369582826129ac914c000e555c8d2b43b42516c/sdks/java/core/src/main/java/org/apache/beam/sdk/io/Compression.java#L129)writing Zip files. I will have the documentation updated! Thank you for bringing this to our attention @zstatmanweil

the documentation is still not updated !
