### ISSUE TITLE
How to achieve schema changes for the mysql to bq cdc. Any ideas to do that seamlessly without redeploying it.

### ISSUE THREAD

**Issue by asvseb** [GoogleCloudPlatform/DataflowTemplates#97]
How to achieve schema changes for the mysql to bq cdc. Any ideas to do that seamlessly without redeploying it.

**Comment by pabloem** [comment]
Unfortunately, currently this is not possible. In the future, changes are planned to support schema changes more seamlessly (e.g. json-based data encoding, and the Dataflow pipeline will live-lookup schemas).

**Comment by duizendstra** [comment]
I am working on a pipeline that does a live lookup of the schema. Is it possible to see the planned changes/approach to see if I can learn/or contribute?

**Comment by pabloem** [comment]
I have not yet quite figured this out yet. A possibility  is to have the data encoded in JSON format, use a single PubSub topic, and periodically update the schemas in data catalog. On the merge side and the changelog writing side, whenever we see a schema update, then we update the BQ table.

**Comment by asvseb** [comment]
Thanks Pabloem, I have my own pipeline using single pubsub topic and schema evolution working fine.

My question is on merge side, I have a list of tables for which I need merging (table list is in a file in a bucket) and in a single dataflow job I am calling merging in parallel for 200+ tables for as much data integrity.  I see that merging is triggered only seconds apart (ideally need to be at same time as much as possible) and also noticed that if it previous merging iteration for 200 tables are not finished, the next sequence still starts executing. I also noted that concurrent merging causes duplicates at BQ side. I used the GenerateSequence option to schedule merging every 90 secs and our requirement is to get to 60secs for 200 to 500 tables. 

Is there any way to skip a merging iteration if a previous merging is already running. ??

**Comment by Ace-Bansal** [comment]
Can someone please explain to me how exactly does Data Catalog fit into this and how are we using it here currently?
Also can you please take a look at this [similar issue](https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/144#issue-639424116) where I've asked a couple of questions?

**Comment by gkstechie** [comment]
@Ace-Bansal  This projet uses custom data catalog entry in single topic mode, which GCP didn't give support for update/edit entry so we can't update schema in that mode. When I try with delete and create again resource (entry with same name) was not available as it requires some time to free up the resources. 

In case of multi topic mode, this project uses pubsub entry which can be updated and GCP supports API for those operations. so datacatalog will be fit only in multi topic mode as of my knowledge.

Other than that we may need to identify ways to compare old and new schema or to get new updated columns or data types so that we can update BQ table schema.

Please let me know your suggestion, as I would also like to contribute to this project @pabloem

**Comment by asvseb** [comment]
Hi,
The schema changes is possible with the approach mentioned by pabloem on Apr 13 using JSON encoding.

**Comment by gkstechie** [comment]
Hi,
In multi-topic mode it is possible (as it is using pubsub entry based catalog) but in single topic mode it is not possible because this solution uses custom catalog as google not implemented update API for custom catalog. Even though data encoded in JSON schema can't be updated in the custom catalog.

@asvseb @pabloem

**Comment by krattan406** [comment]
Hi, 
I am also facing the issue of  schema changes not being supported. I am using debezium embedded connector for mysql to stream data into bigquery with single topic. Whenever there is a schema change the connector has to be redeployed. Please let me know if anyone found a solution to this issue or have any ideas how to resolve having to redeploy the connector. Converting to JSON is not feasible. Thanks!

@pabloem @gkstechie

**Comment by pabloem** [comment]
unfortunately I don't have time to spend working on this. It's a difficult problem to achieve with Dataflow, as coders need to be updated, and BQ schemas aslsow ould need to be updated on the fly.
